import { CssProperty, SetInternalElementStyleOptions } from '../type/common.d';
export declare const getRandomStr: (pasLen: any) => string;
export declare const getCssPropertyString: (cssProperty?: CssProperty) => string;
export declare const getDomRandomClass: (classNamePrefix: string) => string;
export declare const setStyle: (cStyleItem: SetInternalElementStyleOptions, selectorString: string) => string;
export declare function addUnit(value?: string | number): string;
export declare function filterAttrs(obj: any, customAttr?: string[]): any;
export declare const getStyle: (styles: CssProperty) => CssProperty;
export declare function colorRgb(color: string): string;
export declare const rgb2rgba: (color: string, alp?: number) => string;
export declare const splitArray: (arr: unknown[], n?: number) => unknown[];
export declare function getUuid(): string;
export declare const getAQILevel: (value: any) => "level7" | "level1" | "level2" | "level3" | "level4" | "level5" | "level6";
export declare const getPollutionHtml: (htmlArray: {
    [key: string]: string;
}[], name?: string) => string;
export declare const replacePollutionHtml: (optionString: string) => string;
export declare const getValueOrDefaultValue: (value: any, defaultValue?: string | number | boolean) => any;
export declare function deepCloneFun(target: any): any;
export declare function deepMergeFun(obj1: any, obj2: any): any;
export declare function useDebounce<F extends (...args: unknown[]) => unknown>(fn: F, duration?: number): () => void;
