window.publicGlobalVariables = {
  "regionData": [],
  "deptIframeSrc": "",
  "isFrame": false,
  "supervisorPopParams": {},
  "supervisorPopName": "",
  "selectMapCode": "350700000000",
  "dialogParams2": {},
  "dialogName2": "",
  "dialogParams": {},
  "dialogName": "",
  "dialogInstance": "",
  "npServiceBaseUrl": "http://192.168.24.106:10157",
  "indicatorType": "",
  "menuToUrl": "http://192.168.0.202:7777/lego-generated-apps/lego_file/app/src/27d54c897f0f4ba18421a7b587fe4ce4_12_6/index.html",
  "moreNews": "http://192.168.24.197:7777",
  "brainBaseUrl": "https://172.26.203.20:10156",
  "themeArr": [
    {
      "jscSkinName": "绿色主题",
      "jscSkinCode": "green",
      "skinCode": "dark-blackish-green",
      "skinName": "绿色版"
    },
    {
      "jscSkinName": "蓝色主题",
      "jscSkinCode": "blue",
      "skinCode": "blue",
      "skinName": "蓝色版"
    },
    {
      "jscSkinName": "PC浅色版",
      "jscSkinCode": "pc-light",
      "skinCode": "pc-light",
      "skinName": "PC浅色版"
    }
  ],
  "cloudLoaded": false,
  "applicaiton": {
    "title": "--",
    "description": "--",
    "todate": "--",
    "deptCode": "",
    "isTabSource": false
  },
  "showLevelTwoPop": false,
  "showLevelTwoPopComponent": "allApplicationCallRelationComponent",
  "waterCode": "",
  "isPageVisible": true,
  "toolName": "大气监测站",
  "toolType": "airToolComponent",
  "isMapTool": false,
  "isTool": true,
  "lxzVariableObj": {
    "lxzDialogArr": [],
    "common": {
      "apiBaseUrl": "http://192.168.0.65:7777/",
      "chatMessagePath": "v1/chat-messages",
      "recommendQuestionPath": "v1/messages",
      "skin": "dark-blackish-green",
      "noDataImgSrc": "/lego-generated-apps/lego_file/res/2025-03-22/220deb6d91f34515a786408e4743eba8.png",
      "dialogStatus": false,
      "isDisable": false,
      "dialogOpacity": 0,
      "closeDialogQuestionArr": [
        "关闭弹窗",
        "查看地图",
        "查看大屏",
        "关闭弹窗。",
        "查看地图。",
        "查看大屏。"
      ],
      "lockIcon": "/lego-generated-apps/lego_file/res/2025-03-27/c01dc5ba81ac41e2ba492ac117aa1657.svg",
      "notLockIcon": "/lego-generated-apps/lego_file/res/2025-03-27/7ef69c088f284af6bd813b6a3be093ce.svg"
    },
    "defaultAppName": "",
    "voiceParam": {
      "appId": "3ec780a1-67e5-4e5b-90f1-20a5060c9585",
      "getParamIp": "http://192.168.0.65:7777/znxl-service-pro-v2",
      "getParamContext": "dify/dify-app/detail",
      "userToken": "",
      "conversationId": "",
      "apiToken": "",
      "ragFlowToken": ""
    }
  },
  "typeCode": "",
  "waterPopData": {
    "type": "",
    "POINT_CODE": "",
    "MONITORTIME": "",
    "ASSESSTYPE": ""
  },
  "isWaterPop": false,
  "mapChangeAllStatusParams": {},
  "DEFAULT_REGION_NAME": "南平市",
  "DEFAULT_REGION_CODE": "350700000000",
  "isTable": false,
  "countryTime": "",
  "constructTime": "",
  "carbnTime": "",
  "holdTime": "",
  "offshoreTime": "",
  "waterTime": "",
  "cityTime": "",
  "socketIp": "http://192.168.0.202:7777/socketPath",
  "socketPath": "",
  "socketRoom": "admin",
  "baseGlobalData": {},
  "serviceBaseUrl": "http://192.168.24.106:10157",
  "prodBasePath": "",
  "bottomMenuExpandState": false,
  "syTrendAnalysisUrl": "http://192.168.0.202:7777/thswater/envquality/analysis/changen/trend_analysis_along_the_route_month.vm",
  "casLoginParams": "http://192.168.0.202:7777/cas/redirect/by/cas?gotourl=",
  "casLoginHost": "http://192.168.0.202:7777/cas/login?service=",
  "businessDialog": {
    "dialogName": "",
    "dialogParmas": ""
  },
  "isShowSubject": true,
  "maxNavItemCount": 8,
  "isShowSubjectCheckbox": true,
  "navMenuItemActive": {
    "label": "",
    "name": ""
  },
  "oldViewDialog": false,
  "circleBgVisible": false,
  "enterUrl": "http://192.168.0.202:7777/web-portal",
  "integratedQuery": {},
  "headAlign": "left",
  "serviceBasePath": "/service/serviceinterface/search/run.action?token=dcp",
  "showNoviceGuide": false,
  "mapBaseUrl": "http://192.168.0.202:8999/mapgo5.0/preview.html",
  "isMapLoaded": false,
  "regionaQuery": {},
  "theme": "蓝色主题",
  "casLoginUrl": "http://192.168.0.202:7777/cas/",
  "isSelectedBg": 0,
  "isLoop": true,
  "lxsAppUrl": "http://192.168.0.202:7777/idata-micro/#/idatamicro/ai/aiws-home",
  "lxsServiceBaseUrl": "http://192.168.0.202:7777",
  "contentComponent": "cockpitAllComponent",
  "currentIndex": 0,
  "intervalId": "",
  "toDayTime": "",
  "toMonthTime": "",
  "bottomMenuButtonText": "概览",
  "REGION_CODE": "350700000000",
  "showPop": false,
  "showPopComponent": "shapePopComponent",
  "REGION_NAME": "福建省",
  "loopId": "",
  "isSetLoop": false,
  "loginByCasConfig": {
    "open": true,
    "casUrl": "http://192.168.0.202:7777/cas",
    "serviceUrl": "http://192.168.0.202:7777/cas/redirect/by/cas",
    "getUserTokenUrl": "http://192.168.0.202:7777/cas/security/usertoken"
  },
  "appScaleMode": "",
  "activeTheme": "蓝色主题"
};