import type { DetailStatusStackType } from '../interfaces/common';
import { ObjectSubClassInfo } from '../interfaces/advanced-search';
export declare const SET_SEARCHPANELSTATUS = "SET_SEARCHPANELSTATUS";
export declare const SET_LAYERPANELSTATUS = "SET_LAYERPANELSTATUS";
export declare const SET_THREEDFLYPANELSTATUS = "SET_THREEDFLYPANELSTATUS";
export declare const SET_BOX_SELECTION_STATUS = "SET_BOX_SELECTION_STATUS";
export declare const SET_DIRECTORYPANELSTATUS = "SET_DIRECTORYPANELSTATUS";
export declare const SET_BUSSINESSLAYERPANELSTATUS = "SET_BUSSINESSLAYERPANELSTATUS";
export declare const SET_SCENEPANELSTATUS = "SET_SCENEPANELSTATUS";
export declare const SET_MAPANALYSISSTATUS = "SET_MAPANALYSISSTATUS";
export declare const SET_AREAACTIVE = "SET_AREAACTIVE";
export declare const SET_LAYER_DRAW_RESULT_POP_STATUS = "SET_LAYER_DRAW_RESULT_POP_STATUS";
export declare const SET_THREEDFLYPANEL_EXIST = "SET_THREEDFLYPANEL_EXIST";
export declare const SET_ACTIVEOBJECTDATA = "SET_ACTIVEOBJECTDATA";
export declare const SET_SEARCHDETAILSSTATUS = "SET_SEARCHDETAILSSTATUS";
export declare const SET_BOX_SELECTION_PANEL_EXIST = "SET_BOX_SELECTION_PANEL_EXIST";
export declare const SET_DETAILS_COMPONENT_NAME = "SET_DETAILS_COMPONENT_NAME";
export declare const SET_DETAILS_COMPONENT_PARAMS = "SET_DETAILS_COMPONENT_PARAMS";
export declare const SET_DETAILS_COMPONENT_STATUS_STACK = "SET_DETAILS_COMPONENT_STATUS_STACK";
export declare const SET_DETAILS_COMPONENT_STATUS_STACK_IS_FINISH_POP = "SET_DETAILS_COMPONENT_STATUS_STACK_IS_FINISH_POP";
export declare const SET_MAPBOX_LISTDATATYPE_BTN_LIGHT_STATUS = "SET_MAPBOX_LISTDATATYPE_BTN_LIGHT_STATUS";
export declare const SET_MAP_BOX_DRAW_PARAMS = "SET_MAP_BOX_DRAW_PARAMS";
export declare const SET_LINE_AREA_LAYER_IDS = "SET_LINE_AREA_LAYER_IDS";
export declare const ADVANCE_SEARCH_ACTIVE_ENTITY = "ADVANCE_SEARCH_ACTIVE_ENTITY";
declare const _default: import("vuex").Store<{
    searchPanelShow: boolean;
    layerPanelShow: boolean;
    threeDFlyPanelShow: boolean;
    mapBoxSelectionShow: boolean;
    directoryPanelShow: boolean;
    bussinessLayerPanelShow: boolean;
    isOpenSceneHome: boolean;
    mapAnalysisVisible: boolean;
    layerDrawingResultPopShow: boolean;
    areaActive: {
        code: string;
        codeType: string;
        name: string;
    };
    stepHistoryData: {};
    isThreeDFlyPanelExist: boolean;
    activeObjectData: {};
    searchDetailsShow: boolean;
    isBoxSelectionPanelExist: boolean;
    detailsComponentName: string;
    detailsComponentParams: {};
    detailStatusStack: DetailStatusStackType[];
    mapBoxDrawParams: {};
    activeLayerResultCode: string;
    boxSelectPointDetailsParam: {};
    commonPopupVisible: boolean;
    commonPopupInfos: {
        title: string;
        titleIconClasses: string;
        btnInfos: {
            text: string;
        }[];
        message: never[];
    };
    mutexComponentName: string;
    seeMoreComponentName: string;
    seeMorePointCode: string;
    seeMorePointType: string;
    seeMorePointTimeType: string;
    seeMorePointEntityCode: string;
    lineSLayerIds: never[];
    advanceSearchActiveEntity: ObjectSubClassInfo;
}>;
export default _default;
