export declare enum ComponentEvent {
    AreaSelect = "areaSelect",
    RemoveCircleFlight = "removeCircleFlight",
    Remove = "remove",
    Add = "add",
    RegionCode = "regionCode",
    Buffer = "buffer",
    GoTo = "goTo",
    GetExtentByADCode = "getExtentByADCode",
    ClearFlight = "clearFlight",
    HidePage = "hidePage",
    CancelSelectEffect = "cancelSelectEffect",
    CircleFlightStart = "circleFlightStart",
    RemoveLayers = "removeLayers",
    ChangeLegendVisibility = "changeLegendVisibility",
    AddLayers = "addLayers",
    ClearDraw = "clearDraw",
    GetIntoFeature = "getIntoFeature",
    BoxSelectRemoveHightLayer = "boxSelectRemoveHightLayer",
    SetLayersData = "setLayersData",
    RegisterMapEvent = "registerMapEvent",
    StartDraw = "startDraw",
    RemoveMapEvent = "removeMapEvent",
    UpdateLegendRenderer = "updateLegendRenderer",
    SearchResultListSelected = "searchResultListSelected",
    WaterThreeDFly = "waterThreeDFly"
}
export declare enum PageEvent {
    SendMessage = "sendMessage",
    OpenAdvancedDetail = "openAdvancedDetail",
    CloseAdvancedDetail = "closeAdvancedDetail",
    ChangeAroundDistance = "changeAroundDistance",
    SelectedPointObject = "selectedPointObject",
    GetBoxSelectType = "getBoxSelectType",
    ShowFilterDetail = "showFilterDetail",
    SwitchAreaObj = "switchAreaObj",
    OpenAdvancedSearch = "openAdvancedSearch",
    ClickIntelligentSearch = "clickIntelligentSearch",
    CloseThreeDFly = "closeThreeDFly",
    CloseBoxSelection = "closeBoxSelection",
    SendAroundInfo = "sendAroundInfo",
    SendExtent = "sendExtent",
    HandleAdvancedResultDetailVisible = "handleAdvancedResultDetailVisible",
    ResetAdvanceDetailStatus = "resetAdvanceDetailStatus"
}
